# Generated by Django 5.1.3 on 2024-12-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimba_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images/'),
        ),
        migrations.AddField(
            model_name='savings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images/'),
        ),
    ]
